version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo?schema=public
      NEXTAUTH_URL: http://localhost:3003
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      BCRYPT_SALT_ROUNDS: 10
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3003:3000"
    command: sh -c "npx prisma migrate deploy && node server.js"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
